# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Start with a base Python image
FROM python:3.13-slim

# Install curl to fetch the UV installation script
RUN apt-get update && apt-get install -y curl && apt-get clean

# Set the working directory
WORKDIR /app

# Copy the project files into the Docker image
COPY . .

# Install UV using curl
RUN curl -LsSf https://astral.sh/uv/install.sh | sh

# Create a virtual environment and activate it
RUN uv venv && . .venv/bin/activate

# Install the project dependencies
RUN uv pip install .

# Expose the necessary port (if applicable)
# EXPOSE 8000 

# Define the command to run the MCP server
ENTRYPOINT ["uv", "run", "src/neodb/server.py", "<API_BASE>", "<ACCESS_TOKEN>"]
